const defaultTheme = require("tailwindcss/defaultTheme");
module.exports = {
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    rotate: {
      70: "70deg",
      290: "290deg",
    },
    maxWidth: {
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
      "5rem": "5rem",
      "5.5rem": "5.5rem",
      "5.7rem": "5.7rem",
      "15rem": "15rem",
    },
    cursor: {
      auto: "auto",
      default: "default",
      pointer: "pointer",

      wait: "wait",
      text: "text",

      move: "move",
      "not-allowed": "not-allowed",

      crosshair: "crosshair",
    },
    maxHeight: {
      0: "0",
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
      full: "100%",
      "50vh": "50vh",
      "10rem": "10rem",
    },
    screens: {
      xs: "240px",
      ...defaultTheme.screens,
    },

    minHeight: {
      0: "0",
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
      full: "100%",
      "25vh": "25vh",
      "80vh": "80vh",
    },
    extend: {
      blur: {
        xs: "1px",
      },
      animation: {
        wiggle: "wiggle 1s ease-in-out infinite",
        test1: "test 10s linear infinite",
      },
      keyframes: {
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        test: {
          "0%": {
            transform: "translateX(100%)",
          },
          "100%": { transform: "translateX(-100%)" },
        },
      },
      top: {
        top30rem: "30rem",
        top5rem: "5rem",
      },
      height: {
        "20rem": "20rem",
        "21rem": "21rem",
        "22rem": "22rem",
        "28rem": "28rem",
        "29rem": "29rem",
        "25rem": "25rem",
        "26rem": "26rem",
        "70vh": "70vh",
        "80vh": "80vh",
        "300px": "300px",
      },
      zIndex: {
        1000: 1000,
        500: 500,
        100: 100,
        3000: 3000,
        4000: 4000,
        2000: 2000,
        6666: 6666,
        5555: 5555,
        7777: 7777,
        8888: 8888,
        9999: 9999,
      },
      inset: {
        "28%": "28%",
        "40%": "40%",
        "42%": "42%",
        "14.5%": "14.5%",
        "21%": "21%",
        "22%": "22%",
        "22rem": "22rem",
        "23rem": "23rem",
        "30rem": "30rem",
        "28rem": "28rem",
        "27rem": "27rem",
        "26rem": "26rem",
        "25rem": "25rem",
        "-5rem": "-4.5rem",
      },
      colors: {
        BgMain: "#FFF4DE",
        MainColor: "#FFBFE0",
        BgMainOga2: "#FFE3DE",
        SecondaryColor: " #FEC0E0",
        OgaPink2: "#FE4860",
        OgaLightPink: "#FEF1F3",
        DarkPink: "#E04E99",
        Pinkv2: "#DB3088",
        WhiteColor: "#FFFFFF",
        GreenColor: "#7ACA2E",
        BlueColor: "#00395D",
        GreenCard: "#00AC65",
        DarkBlueColor: "#073355",
        BeigeColor: "#FFE0C1",
        Gradien1: "#CC9337",
        Gradien2: "#E8D0A7",
        OrangeColor: "#FB8C00",
        RedColor: "#E05468",
        GreyColor: "#757A88",
        LightGreyColor: "#B7B7B7",
        DarkRedColor: "#F95e5e",
        LightGreyColor: "#EDEDED",
        CartCardBgColor: "#FAF8f8",
        LightOrangeColor: "#FD7843",
        LightGreenColor: "#41CC6C",
        SkyBlueColor: "#1FAFFF",
        LightVioletColor: "#5E79F9",
        PinkRedColor: "#DB3088",
        VoucherColor: "#D93588",
        VoucherBgColor: "#FFEFF7",
        FullfillmentCartGrey: "#F7F7F7",
        FadedBlueColor: "#EBEBEB",
        FbColor: "#3B5999",
        GoogleColor: "#E0492F",
        BlueDownyColor: "#EBEBEB",
      },
      fontFamily: {
        Nunito: ["Nunito Sans"],
        Gotham: ["Gotham"],
        NunitoBold: ["Nunito Sans Bold"],
        Quicksand: ["Quicksand"],
        QuicksandRegular: ["QuicksandRegular"],
        OpenSans: ["OpenSans"],
        OpenSansExtraBold: ["OpenSansExtraBold"],
        OpenSansSemiBold: ["OpenSansSemiBold"],
        QuicksandLight: ["QuicksandLight"],
      },
      boxShadow: {
        OgalaShadow: "0px 3px 6px #E2C391",
        InputShadow: "0px 3px 6px #E7D2AF",
        CarouselControleShadow: "0px 3px 6px #00000029",
        CookiesShadow: "0px -3px 6px #00000029",
      },
      fontSize: {
        NavFont: "17px",
        CollectionFontSize: "22px",
        CollectionDescFontSize: "16px",
        FifteenPx: "15px",
        twelvePx: "12px",
        ElevenPx: "11px",
        TenPx: "10px",
        NinePx: "9px",
      },
      padding: {
        Padding2XL: "18rem",
        Padding28rem: "28rem",
        Padding35rem: "35rem",
        Padding22rem: "22rem",
        Padding30: "18%",
      },
      scale: {
        Scale60: ".65",
        Scale2: "2",
        Scale21: "2.1",
        Scale23: "2.3",
        Scale25: "2.5",
      },

      margin: {
        "65vh": "65vh",
        "50vh": "50vh",
        "35vh": "35vh",
      },
      width: {
        "30%": "30%",
        "38%": "38%",
      },
      // screens: {
      // xs: "240px",

      // ...defaultTheme.screens,
      // sm: "640px",
      // => @media (min-width: 640px) { ... }
      //  md: "767px",
      // => @media (min-width: 768px) { ... }
      //  lg: "1023px",
      // => @media (min-width: 1024px) { ... }
      //  xl: "1281px",
      // => @media (min-width: 1280px) { ... }
      // "2xl": "1537px",
      // => @media (min-width: 1536px) { ... }
      //  },
    },
  },
  variants: {
    extend: { backgroundColor: ["active"], scale: ["active"] },
  },
  plugins: [require("@tailwindcss/line-clamp")],
};
